area:a2a:
  - changed-files:
    - any-glob-to-any-file:
      - ag2/a2a/**
      - test/a2a/**

area:a2ui:
  - changed-files:
    - any-glob-to-any-file:
      - ag2/a2ui/**
      - test/a2ui/**

area:acp:
  - changed-files:
    - any-glob-to-any-file:
      - ag2/acp/**
      - test/acp/**

area:ag-ui:
  - changed-files:
    - any-glob-to-any-file:
      - ag2/ag_ui/**
      - test/ag_ui/**

area:mcp:
  - changed-files:
    - any-glob-to-any-file:
      - ag2/mcp/**
      - test/mcp/**

area:network:
  - changed-files:
    - any-glob-to-any-file:
      - ag2/network/**
      - test/network/**

area:extensions:
  - changed-files:
    - any-glob-to-any-file:
      - ag2/extensions/**
      - test/extensions/**
      - website/docs/user-guide/extensions/**

area:docs:
  - changed-files:
    - any-glob-to-any-file:
      - website/**
      - docs/**
      - notebook/**

area:actions:
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/**

area:deps:
  - changed-files:
    - any-glob-to-any-file:
      - pyproject.toml
      - uv.lock
