# Copyright (c) 2023 - 2025, AG2ai, Inc., AG2ai open-source projects maintainers and core contributors
#
# SPDX-License-Identifier: Apache-2.0

# Taken over from https://github.com/openai/openai-python/blob/v2.41.0/src/openai/types/chat/chat_completion.py

# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from collections.abc import Callable
from typing import Any, Literal

from ._models import BaseModel
from .chat_completion_message import ChatCompletionMessage
from .chat_completion_token_logprob import ChatCompletionTokenLogprob
from .completion_usage import CompletionUsage

__all__ = [
    "ChatCompletion",
    "Choice",
    "ChoiceLogprobs",
    "Moderation",
    "ModerationInput",
    "ModerationInputError",
    "ModerationInputModerationResults",
    "ModerationInputModerationResultsResult",
    "ModerationOutput",
    "ModerationOutputError",
    "ModerationOutputModerationResults",
    "ModerationOutputModerationResultsResult",
]


class ChoiceLogprobs(BaseModel):
    content: list[ChatCompletionTokenLogprob] | None = None
    """A list of message content tokens with log probability information."""

    refusal: list[ChatCompletionTokenLogprob] | None = None
    """A list of message refusal tokens with log probability information."""


class Choice(BaseModel):
    finish_reason: Literal["stop", "length", "tool_calls", "content_filter", "function_call"]
    """The reason the model stopped generating tokens.

    This will be `stop` if the model hit a natural stop point or a provided stop
    sequence, `length` if the maximum number of tokens specified in the request was
    reached, `content_filter` if content was omitted due to a flag from our content
    filters, `tool_calls` if the model called a tool, or `function_call`
    (deprecated) if the model called a function.
    """

    index: int
    """The index of the choice in the list of choices."""

    logprobs: ChoiceLogprobs | None = None
    """Log probability information for the choice."""

    message: ChatCompletionMessage
    """A chat completion message generated by the model."""


class ModerationInputModerationResultsResult(BaseModel):
    categories: dict[str, bool]
    """
    A dictionary of moderation categories to booleans, True if the input is flagged
    under this category.
    """

    category_applied_input_types: dict[str, list[Literal["text", "image"]]]
    """Which modalities of input are reflected by the score for each category."""

    category_scores: dict[str, float]
    """A dictionary of moderation categories to scores."""

    flagged: bool
    """A boolean indicating whether the content was flagged by any category."""

    model: str
    """The moderation model that produced this result."""

    type: Literal["moderation_result"]
    """
    The object type, which was always `moderation_result` for successful moderation
    results.
    """


class ModerationInputModerationResults(BaseModel):
    model: str
    """The moderation model used to generate the results."""

    results: list[ModerationInputModerationResultsResult]
    """A list of moderation results."""

    type: Literal["moderation_results"]
    """The object type, which is always `moderation_results`."""


class ModerationInputError(BaseModel):
    code: str
    """The error code."""

    message: str
    """The error message."""

    type: Literal["error"]
    """The object type, which is always `error`."""


ModerationInput = ModerationInputModerationResults | ModerationInputError


class ModerationOutputModerationResultsResult(BaseModel):
    categories: dict[str, bool]
    """
    A dictionary of moderation categories to booleans, True if the input is flagged
    under this category.
    """

    category_applied_input_types: dict[str, list[Literal["text", "image"]]]
    """Which modalities of input are reflected by the score for each category."""

    category_scores: dict[str, float]
    """A dictionary of moderation categories to scores."""

    flagged: bool
    """A boolean indicating whether the content was flagged by any category."""

    model: str
    """The moderation model that produced this result."""

    type: Literal["moderation_result"]
    """
    The object type, which was always `moderation_result` for successful moderation
    results.
    """


class ModerationOutputModerationResults(BaseModel):
    model: str
    """The moderation model used to generate the results."""

    results: list[ModerationOutputModerationResultsResult]
    """A list of moderation results."""

    type: Literal["moderation_results"]
    """The object type, which is always `moderation_results`."""


class ModerationOutputError(BaseModel):
    code: str
    """The error code."""

    message: str
    """The error message."""

    type: Literal["error"]
    """The object type, which is always `error`."""


ModerationOutput = ModerationOutputModerationResults | ModerationOutputError


class Moderation(BaseModel):
    input: ModerationInput
    """Moderation for the request input."""

    output: ModerationOutput
    """Moderation for the generated output."""


class ChatCompletion(BaseModel):
    id: str
    """A unique identifier for the chat completion."""

    choices: list[Choice]
    """A list of chat completion choices.

    Can be more than one if `n` is greater than 1.
    """

    created: int
    """The Unix timestamp (in seconds) of when the chat completion was created."""

    model: str
    """The model used for the chat completion."""

    object: Literal["chat.completion"]
    """The object type, which is always `chat.completion`."""

    moderation: Moderation | None = None
    """
    Moderation results for the request input and generated output, if moderated
    completions were requested.
    """

    service_tier: Literal["auto", "default", "flex", "scale", "priority"] | None = None
    """The service tier used for processing the request."""

    system_fingerprint: str | None = None
    """This fingerprint represents the backend configuration that the model runs with.

    Can be used in conjunction with the `seed` request parameter to understand when
    backend changes have been made that might impact determinism.
    """

    usage: CompletionUsage | None = None
    """Usage statistics for the completion request."""


class ChatCompletionExtended(ChatCompletion):
    message_retrieval_function: Callable[[Any, "ChatCompletion"], list[ChatCompletionMessage]] | None = None
    config_id: str | None = None
    pass_filter: Callable[..., bool] | None = None
    cost: float | None = None
