# Copyright (c) 2026, AG2ai, Inc., AG2ai open-source projects maintainers and core contributors
#
# SPDX-License-Identifier: Apache-2.0

from abc import ABC, abstractmethod
from collections.abc import Iterable
from dataclasses import dataclass
from typing import Any

from autogen.beta.agent import Agent, AgentReply
from autogen.beta.annotations import Context
from autogen.beta.config import ModelConfig
from autogen.beta.context import ConversationContext, Stream
from autogen.beta.events import BinaryResult, ModelResponse
from autogen.beta.history import History
from autogen.beta.hitl import HumanHook
from autogen.beta.middleware.base import MiddlewareFactory
from autogen.beta.observers import Observer
from autogen.beta.stream import MemoryStream
from autogen.beta.tools.tool import Tool


@dataclass(slots=True)
class VoiceInput:
    content: bytes  # 16-bit PCM bytes
    frame_rate: int
    channels: int


class STTConfig(ABC):
    @abstractmethod
    async def transcribe(self, voice: VoiceInput, context: Context) -> str: ...

    def pipe(self, agent: Agent) -> "VoicePipeline":
        return VoicePipeline(agent, self)


class VoicePipeline:
    def __init__(self, agent: Agent[str], config: STTConfig) -> None:
        self.stt_config = config
        self.agent = agent

    async def ask(
        self,
        voice: VoiceInput,
        stream: Stream | None = None,
        dependencies: dict[Any, Any] | None = None,
        variables: dict[Any, Any] | None = None,
        prompt: Iterable[str] = (),
        config: ModelConfig | None = None,
        tools: Iterable[Tool] = (),
        middleware: Iterable[MiddlewareFactory] = (),
        observers: Iterable[Observer] = (),
        hitl_hook: HumanHook | None = None,
    ) -> "VoiceReply":
        stream = stream or MemoryStream()

        context = ConversationContext(
            stream,
            prompt=list(prompt),
            dependencies=self.agent._agent_dependencies | (dependencies or {}),
            variables=self.agent._agent_variables | (variables or {}),
            dependency_provider=self.agent.dependency_provider,
        )

        text = await self.stt_config.transcribe(voice, context)
        reply = await self.agent._ask(
            text,
            context=context,
            config=config,
            tools=tools,
            middleware=middleware,
            observers=observers,
            hitl_hook=hitl_hook,
        )
        return VoiceReply(reply, self.stt_config)


class VoiceReply:
    __slots__ = (
        "reply",
        "stt_config",
    )

    def __init__(self, reply: AgentReply[str], config: STTConfig) -> None:
        self.reply = reply
        self.stt_config = config

    async def content(
        self,
        *,
        retries: int | float = 0,
    ) -> str | None:
        return await self.reply.content(retries=retries)

    @property
    def response(self) -> ModelResponse:
        return self.reply.response

    @property
    def body(self) -> str | None:
        """Text body of the model's response for this turn."""
        return self.reply.body

    @property
    def files(self) -> list[BinaryResult]:
        """Images generated by the model in this turn (decoded bytes)."""
        return self.reply.files

    @property
    def history(self) -> History:
        return self.reply.history

    async def ask(
        self,
        voice: VoiceInput,
        dependencies: dict[Any, Any] | None = None,
        variables: dict[Any, Any] | None = None,
        prompt: Iterable[str] = (),
        config: ModelConfig | None = None,
        tools: Iterable[Tool] = (),
        middleware: Iterable[MiddlewareFactory] = (),
        observers: Iterable[Observer] = (),
        hitl_hook: HumanHook | None = None,
    ) -> AgentReply[str]:
        text = await self.stt_config.transcribe(voice, self.reply.context)
        return await self.reply.ask(
            text,
            dependencies=dependencies,
            variables=variables,
            prompt=prompt,
            config=config,
            tools=tools,
            middleware=middleware,
            observers=observers,
            hitl_hook=hitl_hook,
        )
